theme = "onedark"
[editor.cursor-shape]
insert = "bar"
[editor]
line-number = "relative"
mouse=false
bufferline="always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
[editor.file-picker]
hidden = false
[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup= "no_op"
pagedown = "no_op"

[editor.lsp]
display-inlay-hints = true
